language: php

dist: trusty

sudo: false

php:
#  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - DB=mysql
  - DB=sqlite

matrix:
  fast_finish: true
#
#  include:
#    - php: 7.0
#      env: PHPCS=1

before_script:
  - composer selfupdate
  - composer install --prefer-dist --no-suggest
  - php bin/cake.php migrations migrate
#  - if [[ $PHPCS = 1 ]]; then composer require cakephp/cakephp-codesniffer:~2.1; fi
#  - if [[ $PHPCS != 1 ]]; then composer install; fi
#  - if [[ $PHPCS != 1 ]]; then composer run-script post-install-cmd --no-interaction; fi

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_fc;'

script:
  - vendor/bin/phpunit
#  - if [[ $PHPCS != 1 ]]; then phpunit; fi
#  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
