language: 
  - php
  
dist: xenial

sudo: true

git:
  depth: false

php:
  - 7.4
  
env:
    global:
      - DB=mysql
      - XDEBUG_MODE=coverage
      - MY_REPORTS_PATH=/home/travis/build/giumar/fortunecookies
      - CC_TEST_REPORTER_ID=0b3e8b1e905bbea0d9d991090bf84a74404b256065bac4216a89890741416b31

services:
  - mysql

mysql:
  database: test_fc
  username: root
  encoding: utf8  
  
jobs:
  fast_finish: true

addons:
    code_climate:
        repo_token: 0b3e8b1e905bbea0d9d991090bf84a74404b256065bac4216a89890741416b31
    sonarcloud:
        organization: "giumar"
        token: $SONAR_TOKEN


before_script:
  - composer selfupdate
  - composer install --prefer-dist --no-suggest --no-interaction
  - cp ./.travis_app_local_mysql.txt ./config/app_local.php
  - php bin/cake.php migrations migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_fc;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS fc;'
  - nvm install --lts node

install:
  #- npm install

script:
  - vendor/bin/phpunit --coverage-clover=${MY_REPORTS_PATH}/phpunit-coverage.xml --log-junit=${MY_REPORTS_PATH}/phpunit-tests.xml --color=auto
  - cp ${MY_REPORTS_PATH}/phpunit-coverage.xml build/logs/clover.xml
  - sonar-scanner

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
