language: php

dist: trusty

sudo: true

php:
  - 7.1
  - 7.4

env:
  - DB=mysql
#  - DB=sqlite

services:
  - mysql

mysql:
  database: test_fc
  username: root
  encoding: utf8  
  
matrix:
  fast_finish: true

addons:
    code_climate:
        repo_token: 0b3e8b1e905bbea0d9d991090bf84a74404b256065bac4216a89890741416b31
    sonarqube:
        token:
          secure: $SONAR_TOKEN


before_script:
  - composer selfupdate
  - composer install --prefer-dist --no-suggest --no-interaction
  - cp ./.travis_app_local_mysql.txt ./config/app_local.php
  - php bin/cake.php migrations migrate

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_fc;'

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=phpunit.xml --color=auto
  - sonar-scanner

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
