# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - export DEBIAN_FRONTEND=noninteractive
          - apt-get update
          - apt-get -y install sudo zip unzip php php-xdebug php-intl php-mbstring php-pdo* php-mysql php-sqlite3 composer phpunit
          - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
          - sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
          - apt-get -y install mysql-server mysql-client
          - sudo service mysql start
          - sudo mysql -u root -proot -e "CREATE DATABASE fc IF NOT EXISTS;"
          - sudo mysql -u root -proot -e "CREATE DATABASE test_fc IF NOT EXISTS;"
          - composer install --prefer-dist --no-interaction --no-progress -a
          - php bin/cake.php migrations migrate
