# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19
      - image: circleci/mysql:5.7.30-ram
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test_my_app
          MYSQL_USER: my_app
          MYSQL_PASSWORD: secret
          
    steps:
      - checkout

      #- run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      #- run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - run: "cp config/app.default.php config/app_local.php"
      - run: "sed -i -e 's/localhost/127.0.0.1/g' config/app_local.php"
      - run: "sed -i -e 's/E_ALL/E_ALL \\& ~E_USER_DEPRECATED \\& ~E_DEPRECATED/g' config/app_local.php"
      - run: "sed -i -e 's/test_myapp/test_my_app/g' config/app_local.php"
      - run: "sed -i -e 's/__SALT__/0123456789/g' config/app_local.php"
      #- run: "php bin/cake.php migrations migrate"

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
      #- run: ./vendor/bin/codecept build
      #- run: ./vendor/bin/codecept run